hmcts/sscs-evidence-share

src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java

Spring autowire fix

---

src/main/java/uk/gov/hmcts/reform/sscs/config/SpringConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java

Fix for the health endpoint always returning DOWN.

fix for the health endpoint

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/SSCS-5351

Initial work on CNP configuration

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/SSCS-5351

Fix some Docmosis infra bugs

---

config/pmd/ruleset.xml
src/main/java/uk/gov/hmcts/reform/sscs/domain/BenefitLookup.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/DwpAddress.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentPlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookup.java
src/main/resources/dwpAddresses.json
src/test/java/uk/gov/hmcts/reform/sscs/domain/DwpAddressTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/DocumentPlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/DwpDwpAddressLookupTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/TemplateServiceTest.java

Address Data is built from https://tools.hmcts.net/jira/browse/SSCS-5257
FE Esa select box is here: https://github.com/hmcts/sscs-submit-your-appeal/blob/aa19c5343f2c2d1bb338322fd73eef743abfd32f/steps/compliance/dwp-issuing-office-esa/DWPIssuingOfficeEsa.js#L20

SSCS-5279 - Dwp address data lookup service

---

build.gradle
config/owasp/suppressions.xml
src/e2e/java/helper/EnvironmentProfileValueSource.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
src/e2e/resources/appealCreatedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/controllers/FunctionalTestController.java
src/main/java/uk/gov/hmcts/reform/sscs/docmosis/config/PdfDocumentConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/docmosis/domain/Template.java
src/main/java/uk/gov/hmcts/reform/sscs/docmosis/service/DocmosisPdfGenerationService.java
src/main/java/uk/gov/hmcts/reform/sscs/docmosis/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/sscs/exception/AuthorisationException.java
src/main/java/uk/gov/hmcts/reform/sscs/exception/ClientAuthorisationException.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/service/AuthorisationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentPlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/controllers/FunctionalTestControllerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/docmosis/service/DocmosisPdfGenerationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/AuthorisationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/DocumentPlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-5280
Create the functional tests for the DL6 template
```
[ ] Yes
[ x] No
```

SSCS-5280 Add functional tests for DL6

---

config/owasp/suppressions.xml

https://nvd.nist.gov/vuln/detail/CVE-2018-1258
We need to suppress this so that the build can work.
Looks like other people are suppressing it. https://github.com/search?q=org%3Ahmcts+CVE-2018-1258&type=Code

CVE-2018-1258 - suppression

---

build.gradle

SSCS-3936 - upgrade java logging

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
src/e2e/resources/appealCreatedCallback.json
src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfigTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
src/integrationTest/resources/appealReceivedCallbackWithMrn.json
src/main/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceTest.java

Implement Acceptance criteria in SSCS-5293

SSCS-5393 - Implement Acceptance criteria in SSCS-5293

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf
kubernetes/deployment.template.yaml

Ticket RDO-3629 has details on what we need to do to resolve an intermittent issue with Docmosis service
Example error in the logs:
>I/O error on GET request for "https://docmosis-development.platform.hmcts.net/rs/status": docmosis-development.platform.hmcts.net; nested exception is java.net.UnknownHostException: docmosis-development.platform.hmcts.net

SSCS-5394 - docmosis dns resolution

---

src/main/resources/bootstrap.yaml

bootstrap yaml change

---

src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentManagementServiceWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/DocumentManagementServiceWrapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-5699

SSCS-5699 Stop DL templates from being regenerated multiple times

---

infrastructure/main.tf
infrastructure/prod.tfvars

Reverts hmcts/sscs-evidence-share#120

Revert "Force vault to take latest asb key"

---

src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentManagementServiceWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumerTest.java

add extra retry logic.
log better retry messages.

SSCS-5595 - retry and log better retry messages.

---

src/main/resources/dwpAddresses.json
src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupTest.java

fix junit test
```
[ ] Yes
[ ] No
```

add office to the json file

---

infrastructure/prod.tfvars

turn on send to dwp

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceTest.java

- Feature flag generation of DL6 and DL16 tasks
- Remove evidence share feature flag
- Add extra logging for evidence share

SSCS-6079 Feature flag bulk print tasks

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-6161
Fix build pipeline issue
```
[ ] Yes
[X] No
```

SSCS-6161 - fix build pipeline issue

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-6071
Update venue data
```
[ ] Yes
[X] No
```

SSCS-6071 - update sscs_common version

---

README.md
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/DummyBulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/PrintService.java
src/main/resources/application-local.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/DummyBulkPrintServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6301

SSCS-6301 Skip bulk print service when running local profile

---

charts/sscs-evidence-share/values.yaml
infrastructure/main.tf
infrastructure/variables.tf
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6387
- Add config to scale the robot up
- Random number added to subject of email based on how many robots are configured for that country

Sscs 6387 robotics count

---

src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

If “caseCreated” is populated and of the correct format, then populate the parameter “appealDate” within the robotics JSON with that date. Otherwise set the date to today’s date.
```
[ ] Yes
[ ] No
```

SSCS-6384 Evidence share – Amend Robotics JSON date

---

src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6235

SSCS-6235 Stop attaching bulk scan evidence

---

src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderHelper.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6328

SSCS-6328 Add SC number to footer of further evidence cover sheets

---

src/main/resources/bootstrap.yaml

Revert password to env var standard

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java

https://tools.hmcts.net/jira/browse/SSCS-6547

SSCS-6547 UC changes for Robotics

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

SSCS-6381 - Ready to list event

---

src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/main/resources/schema/sscs-robotics.json
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonValidatorTest.java

https://tools.hmcts.net/jira/browse/SSCS-6288

SSCS-6288 Ready to list Robotic updates

---

src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/config/SMTPConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/config/SmtpConfig.java

fix hardwired SSL trust setting, refactor smtp config
```
[ ] Yes
[ X] No
```

fix hardwired SSL trust setting, refactor smtp config

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-6649

SSCS-6649 Set robotics dwp response date

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-6797

SSCS-6797 Appeal received event for digital cases

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AppealToProceedFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueDirectionFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/e2e/resources/appealToProceedCallback.json
src/e2e/resources/directionIssuedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealToProceedHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealToProceedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-6839

SSCS-6839 Appeal to proceed event

---

src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-6783

SSCS-6783 Default the ready to list fields for robotics

---

infrastructure/demo.tfvars

enable ready to list on demo

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-6931

SSCS-6931 Issue direction post valid states

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-6836

Add missing fields to java model

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-6999

SSCS-6999 change englishCount to 3

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
src/e2e/resources/sendToDwpCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-6869

SSCS-6869 Set created in GAPS from field

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-6993

SSCS-6993 Handle resend to dwp event

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/e2e/resources/issueFurtherEvidenceCallback.json
src/e2e/resources/reissueFurtherEvidenceCallback.json
src/integrationTest/resources/issueFurtherEvidenceCallback.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithAppellantEvidenceAndRepEvidence.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithDwpEvidence.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithRep.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithRepAndEvidenceFromDwp.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithRepEvidence.json

Fixing tests
```
[ ] Yes
[x] No
```

Change dm store url

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueDirectionFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/resources/application-local.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7090

SSCS-7090 Set new case DWP state

---

build.gradle
charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.preview.template.yaml
charts/sscs-evidence-share/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/sscs/domain/email/RoboticsEmailTemplate.java
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

SSCS-6809 Changes to support new PIP AE office added by DWP

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7151

SSCS-7151-issue-direction-npe-fix

---

Jenkinsfile_CNP
build.gradle
charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.preview.template.yaml
config/checkstyle/checkstyle.xml
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/config/SmtpConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7273

SSCS-7273 Use the correct case created date when generating dl6

---

Jenkinsfile_CNP
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-7275

SSCS-7275 Update logo on documents

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6734

SSCS-6734 Improve logging for robotics

---

src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6746

SSCS-6746 Handle filenames with no extension for robotic attachments

---

src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-7372

Sscs 7372 appointee postcode venue

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

SSCS-7372 Use appointee postcode for finding venue for appellantPoscode robotics

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7382

SSCS-7382 Add reciprocal link to associated cases

---

charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfigTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/DocmosisPdfGenerationIt.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/ReissueFurtherEvidenceServiceIt.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
src/integrationTest/resources/config/application_it.properties
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToDwpHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToDwpHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7402

SSCS-7402 Move post creation tasks to evidence share

---

Jenkinsfile_CNP
build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

Temporarily suppressing spring vulnerabilities until we upgrade to Spring 2.3.0

Upgrade gradle to 6.4

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/MockBulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java

- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/SSCS-7478
Handle missing representative names in cover letters to fall back to organisation name or Sir/Madam
```
[ ] Yes
[X] No
```

SSCS-7748 Handle missing representative names in cover letters

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

SSCS-7550: New AirLookup

---

.github/renovate.json
build.gradle
charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/requirements.yaml

Upgrade java chart
Add renovate

SSCS-7587 - Upgrade java chart. Add renovate

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueDirectionHandlerTest.java

Add more error logging for app insights.

SSCS-7695 - Add more logging

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java

Additional retries for flaky functional test
```
[ ] Yes
[ ] No
```

SSCS-7687 additional retries

---

src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java

SSCS-7723 - Robotics – Generation of JSON fails on appointee post code

SSCS-7723 - Robotics – Generation of JSON fails on appointee post code

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

SSCS-7725: Robotics – Stop sending extra documents to the robot

---

Dockerfile
build.gradle

SSCS-7702 - Upgrading to Java 11 - Evidence share

SSCS-7702 - Upgrading to Java 11 - Evidence share

---

build.gradle

fix security vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

[SSCS-7785](https://tools.hmcts.net/jira/browse/SSCS-7785) - Appeal to proceed event should go to robotics

SSCS-7785 - Appeal to proceed event should go to robotics

---

Jenkinsfile_CNP

Change in the jenkins library:
https://github.com/hmcts/cnp-jenkins-library/pull/662
```
[ ] Yes
[x] No
```

Update pipeline method call

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-7535
SSCS-7535 Up common for isScottish
```
[ ] Yes
[X] No
```

SSCS-7535 Up common for isScottish

---

Jenkinsfile_nightly
audit.json
security.sh

enabled security scan

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7832
```
[ ] Yes
[X] No
```

change state

---

security.sh

changed High to Medium

---

build.gradle

SSCS-7806 - Processing documents for reinstatement requests

SSCS-7806 - Processing documents for reinstatement requests

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8119
```
[ ] Yes
[x] No
```

SSCS-8119 Fixing bug

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java

Sscs 8119 fix ready to list clone -WIP

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-8198

SSCS-8198 Hearing subtype robotics

---

src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/main/resources/application-local.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/CoverLetterServiceTest.java

New PR for SSCS-7810 Handle cover letter service failures to be unrecoverable
```
[ ] Yes
[ ] No
```

SSCS-7810 Handle cover letter service failures to be unrecoverable

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8185

SSCS-8185 Set confidential case flag in robotics

---

charts/sscs-evidence-share/values.aat.template.yaml
charts/sscs-evidence-share/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/SSCS-7994
fix pipeline
```
[ ] Yes
[x] No
```

remove env vars

---

charts/sscs-evidence-share/values.aat.template.yaml
charts/sscs-evidence-share/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/SSCS-7994
```
[ ] Yes
[x] No
```

Sscs 7994 joint party added fix

---

security.sh

added folder for reporting

---

build.gradle

SSCS-8214 upgrade sscs-common

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java

re-enable flaky test

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8237
Send exceptions to gaps
```
[ ] Yes
[x] No
```

Sscs 8237 dwp raise exception 2

---

Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/DTSPO-115
Without the lombok change I couldn't run tests in my IDE, and without junit platform upgrade I was hitting a mockito issue on a test I was writing for an upcoming change
```
[ ] Yes
[ ] No
```

Dependency updates

---

charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/DTSPO-115
```
[ ] Yes
[ ] No
```

DTSPO-115 Add launchdarkly config

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8330

SSCS-8330 Move to Elastic Search

---

infrastructure/main.tf

Password is for the account and not api access, I created an Api key now

Fix sendgrid secret

---

config/owasp/suppressions.xml

Suppress for nightly build

---

build.gradle
charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/integrationTest/resources/config/application_it.properties
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

SSCS-8424 - Remove UC flag

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

SSCS-8530: Robotics - send to robotics error

---

src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java

Sonar issue fix

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
src/integrationTest/resources/issueFurtherEvidenceCallbackWithJointParty.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithJointPartyAndEvidenceFromDwp.json
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/FurtherEvidenceLetterType.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java

SSCS-8620 - Issue Edited Docs to Joint Party

SSCS-8620 - Issue Edited Docs to Joint Party

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java

SSCS-8684 - Upgrade Idam Client Only

SSCS-8684 - Upgrade Idam Client Only

---

charts/sscs-evidence-share/values.yaml
gradle/wrapper/gradle-wrapper.properties
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-8757
new urls
```
[ ] Yes
[x] No
```

sscs 8757 new docmosis urls for staging

---

build.gradle

fixed the dependency check

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-8829

SSCS-8829:Add Welsh flag - RIP1 Document

---

src/main/resources/bootstrap.yaml

SSCS-8884: Evidence share – Update PIP AE e-mail address to correct one

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8827

Sscs 8827 single case to draft v3

---

src/main/resources/application.yaml

SSCS-8916 - WTU email in pre-prod

SSCS-8916 - WTU email in pre prod

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-8861

Sscs 8861 rip1 document translation

---

build.gradle

SSCS-8968 - Robotics – PIP AE isn't showing correctly for DwpOriginatingOffice and DwpPresentingOffice

SSCS-8968 - Robotics – PIP AE isn't showing correctly for DwpOriginatingOffice and DwpPresentingOffice

---

build.gradle

Upgrade pdfbox dependency

---

build.gradle

revert SSCS-8894

---

build.gradle
config/owasp/suppressions.xml

SSCS-9046 - fix DC failures

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java

SSCS-9050 - DLA - Update Welsh SSCS1 Form

SSCS-9050 - DLA - Update Welsh SSCS1 Form

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8995

SSCS-8995: CCD UI – Add HMCTS to original senders

---

config/owasp/suppressions.xml

dependency-check-suppressions

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java

https://tools.hmcts.net/jira/browse/SSCS-8879
Adding dwp issue office for dwp
```
[ ] Yes
[x] No
```

sscs 8879 add dla dwp issue office

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9066
Finish jitpack
```
[ ] Yes
[x] No
```

sscs 9066 jitpack change

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9066
move to release
```
[ ] Yes
[x] No
```

Sscs 9066 jitpack

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-8870

SSCS-8870:CCD UI – Implement DWP due date field

---

build.gradle

updated common to use latest robotics mapper 
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9124](url)

updated common

---

audit.json

Ticket has been raised here https://tools.hmcts.net/jira/browse/SSCS-9196 to fix this warning, suppressing for timebeing
```
[ ] Yes
[ ] No
```

Suppress sec warning

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-9117

SSCS-9117 Revert review confidentiality for robotics

---

audit.json
build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java

Sscs 9196 without same site error
Jira Ticket: https://tools.hmcts.net/jira/browse/SSCS-9196

add bean to set sameSite to lax

---

audit.json
build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java

Reverts hmcts/sscs-evidence-share#968

Revert "add bean to set sameSite to lax"

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-8906

SSCS-8906 Bereavement benefit DWP mappings

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/service/TemplateService.java

SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event

SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

SSCS-9122 Handle Robotics Gaps Duplicates

---

config/owasp/suppressions.xml

Verify we have removed enough of the suppressions

Verify we have removed enough of the suppressions

---

config/owasp/suppressions.xml

suppress CVE-2021-33813

---

build.gradle

resolve cve errors

---

config/owasp/suppressions.xml

suppress for a month again

---

build.gradle

updated common with social fund benefit
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8820](url)

SSCS-9061-updated common with social fund benefit

---

build.gradle

SSCS-9378: Resize documents issue seen on representative documents

---

build.gradle

SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer

SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
src/main/resources/application.yaml

SSCS-9362 - Secure doc store

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
src/main/resources/application.yaml

SSCS-9420 - Update doc store client

SSCS-9420 - Update doc store client

---

src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7510

SSCS-7510 Scottish PO box feature flag

---

build.gradle
src/e2e/resources/issueFurtherEvidenceCallback.json
src/e2e/resources/issueFurtherEvidenceExistingReasonableAdjustmentCallback.json
src/e2e/resources/issueFurtherEvidenceReasonableAdjustmentCallback.json
src/e2e/resources/reissueFurtherEvidenceCallback.json
src/e2e/resources/reissueFurtherEvidenceReasonableAdjustmentCallback.json

quick fix for functional tests

quick fix for functional tests

---

build.gradle

SSCS-9567: P1 – Flag to tell users that a case has been affected by t

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9272
Same changes are run in nightly-dev branch
```
[ ] Yes
[ x] No
```

SSCS-9272:Enable mutation test for nightly build

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerHelper.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RequestTranslationCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumerTest.java

https://tools.hmcts.net/jira/browse/SSCS-9429

SSCS-9429 deserialize caseTypeId

---

config/owasp/suppressions.xml

suppress spring dependency check until version upgraded

---

build.gradle

Sscs 9750 amend gaps venue

---

build.gradle

Revert SSCS-9777: Tribunals / Common – Change the document ordering

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9755

SSCS-9755 Child Support Robotics

---

src/main/java/uk/gov/hmcts/reform/sscs/service/PanelCompositionService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ConfirmPanelCompositionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/UpdateOtherPartyHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-9747
Child Support: Set Case to Ready to List or Not Listable
```
[ ] Yes
[ x] No
```

SSCS-9747 changed due date

---

config/owasp/suppressions.xml

CVE-2021-22096 fix
```
[ ] Yes
[ x] No
```

CVE-2021-22096 fix

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
src/integrationTest/resources/issueFurtherEvidenceCallbackWithMultipleOtherPartyRepEvidence.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyAppointeeEvidence.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyEvidence.json
src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyRepEvidence.json
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/FurtherEvidenceLetterType.java
src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/CoverLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-9862

SSCS-9862 Send further evidence to other parties

---

build.gradle

SSCS-9743: Child Support - otherPartyAdded Notification

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-9860
```
[ ] Yes
[ ] No
```

SSCS-9860 SSCS5 - Upload response event

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9841

SSCS-9841 Robotics for sscs5

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10133
```
[ ] Yes
[X] No
```

surpress dependency

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/exception/UnableToContactThirdPartyException.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java

Sscs 9944: SSCS5 - Change DWP to FTA on EXUI: Next Step Events

---

charts/sscs-evidence-share/Chart.yaml

https://tools.hmcts.net/jira/browse/SSCS-10137
```
[ ] Yes
[X] No
```

upgrade charts

---

build.gradle

upgrading log4j to 2.17.1

---

charts/sscs-evidence-share/Chart.yaml

https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```

SSCS-10236 updating helm chart version

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ManualCaseCreatedFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerHelper.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-10068
add supplementary data in create case callbacks
```
[ ] Yes
[x] No
```

sscs 10068 supp data

---

config/owasp/suppressions.xml

SSCS-10280: Supress CVE warnings

---

build.gradle
src/contractTest/resources/application.properties
src/contractTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-10222
```
[ ] Yes
[X] No
```

Revert "Revert "SSCS-10222 Gaps Route Splitting (#1261)" (#1268)"

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10438
```
[ ] Yes
[X] No
```

SSCS-10440 Update Springboot Cre

---

build.gradle
src/contractTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-10223
```
[ ] Yes
[X] No
```

SSCS-10223 Update callback handler

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-10388
```
[x] Yes
[ ] No
```

SSCS-10388 Update Commons

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/SSCS-10443
tagging added to Azure resources.
```
[ ] Yes
[X] No
```

Sscs 10443 azure tagging

---

config/owasp/suppressions.xml

Fix Nightly Builds

---

build.gradle

SSCS-10552-Upgrade-Tomcat: upgrade tomcat

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10555
Upgrading spring core for CVE issues
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ x ] No
```

SSCS-10555 upgraded spring core

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10561
```
[ ] Yes
[X] No
```

SSCS-10561: Dependency Fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```

SSCS-10178 Commons Bump

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandlerTest.java

SSCS-10349 Use update case only to update CAM fields.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10706
Turn Cardiff to LA
```
[ ] Yes
[x] No
```

Turn-Cardiff-LA-On-Common-Bump

---

build.gradle

SSCS-10706 Update pdf email common

---

config/owasp/suppressions.xml

https://github.com/hmcts/sscs-evidence-share/compare/sscs-10746-cve-fix?expand=1
```
[ ] Yes
[ ] No
```

sscs-10746 update for suppress CVE-2022-31569

---

charts/sscs-evidence-share/Chart.yaml

sscsBaseChartUpdate-Java401
```
[ ] Yes
[ ] No
```

sscsBaseChartUpdate-Java401

---

infrastructure/main.tf
infrastructure/providers.tf

alias added for use by non-prod envs
```
[ ] Yes
[ ] No
```

alias added for use by non-prod envs

---

infrastructure/main.tf

count turned off

---

config/owasp/suppressions.xml

extend suppression dates

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```

SSCS-10805-jar-version-update

---

build.gradle
config/owasp/suppressions.xml
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java

https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[ ] No
```

sscs-9874-common-version-update

---

build.gradle
config/owasp/suppressions.xml

SSCS-10841 Common bump

---

build.gradle

Move sscs-common declaration

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/SSCS-10901
```
[ ] Yes
[ ] No
```

SSCS-10901 Add helm alias

---

.github/renovate.json

SSCS-10901 Fix renovate json

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```

SSCS-10882 Fixing Conflicting IDs

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10968
```
[ ] Yes
[ ] No
```

SSCS-10968 cve suppresion

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java

Commons bump

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/SSCS-10924

SSCS-10924 Change to tf managed secret

---

build.gradle
config/owasp/suppressions.xml

CVE-2022-42252
```
[ ] Yes
[ x ] No
```

Tomcat to 9.0.68

---

build.gradle
config/owasp/suppressions.xml

SSCS-11169 - upgrade jackson-databind

---

config/git/pre-commit
config/owasp/suppressions.xml

SSCS-11249 - CVE suppression

---

build.gradle
config/owasp/suppressions.xml

Update dependency check to v8

---

build.gradle
charts/sscs-evidence-share/Chart.yaml
config/owasp/suppressions.xml

renovate and upgrade

---

Dockerfile

Fixing pipeline-Dockerfile update to 3.4.11
```
[ ] Yes
[x] No
```

SSCS-11580 Fixing pipeline

---

src/test/java/uk/gov/hmcts/reform/sscs/service/CoverLetterServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-10978
Code coverage for SSCS-10978
```
[ ] Yes
[x] No
```

Code coverage for SSCS-10978

---

build.gradle
config/owasp/suppressions.xml

CVE Fix 01.06.2023
```
[ ] Yes
[x] No
```

CVE Fix 01.06.2023

---

config/owasp/suppressions.xml

CVE Fix - 27.06.2023
```
[ ] Yes
[x] No
```

CVEFix - 27.06.2023

---

build.gradle

CVE Fix - 30.06.2023
```
[ ] Yes
[x] No
```

CVE Fix - 30.06.2023

---

.github/renovate.json
build.gradle
charts/sscs-evidence-share/Chart.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/CoverLetterServiceTest.java

https://tools.hmcts.net/jira/browse/SSCSCI-459
Refactor CoverLetterService to handle edited urls. 
```
[ ] Yes
[x] No
```

SSCSCI-459

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java

logger statement fix
```
[ ] Yes
[x] No
```

logger statement fix

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SorWriteHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintServiceHelper.java
src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/MockBulkPrintService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/GenericLetterPlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/SorPlaceholderService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SorWriteHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/BulkPrintServiceHelperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/BulkPrintServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/GenericLetterPlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/SorPlaceholderServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-12185
SOR letter via Bulk Print
```
[ ] Yes
[x] No
```

SOR letter via Bulk Print

---

build.gradle

dependency check upgrade to 9.0.6

dependency check update

---

README.md

https://tools.hmcts.net/jira/browse/SSCSCI-645
Empty commit to trigger build

SSCS-CI-645 - update readme

---

charts/sscs-evidence-share/Chart.yaml
charts/sscs-evidence-share/values.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCSCI-638
Extending the check in Reissue Further Evidence to the edited version of the document

SSCSCI-638 - Issue redacted version of document through Reissue Further Evidence

---

build.gradle

Reverts hmcts/sscs-evidence-share#1610

SSCSCI - send-letter-client upgrade

---

config/owasp/suppressions.xml

SSCSSI-34
Bump existing suppression dates

SSCSSI-34: Bump existing suppression dates
